### ISSUE TITLE
不知道你碰到过没有，输入中文的时候emacs停止响应

### ISSUE THREAD

**Issue by sxdxyxy** [et2010/Han#2]
不知道你碰到过没有，输入中文的时候emacs停止响应，我用的是五笔输入法，在org里面有自动补全，最容易死的是在capture 的时候

**Comment by et2010** [comment]
没有发现，我每天都要用。没有用自动补全，因为我发现自动补全很丑而且慢。

**Comment by sxdxyxy** [comment]
那我关掉org里面的自动补全试试看。

**Comment by sxdxyxy** [comment]
如果关掉了自动补全，org 里面写src 不是也没有自动补全了，那在写代码的时候还是不方便吧，请问你是怎么解决的？

**Comment by et2010** [comment]
可以补全的，`C-c '`在打开的buffer里编辑就好了

**Comment by sxdxyxy** [comment]
C-c ' 里面有语法高亮，但没有补全。不知道你的是不是这样的。

**Comment by et2010** [comment]
我记得有的。补充：刚试过，确实有

**Comment by sxdxyxy** [comment]
那我关掉org里面的自动补全试试看。
